apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storyteller
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: storyteller
    newName: rg.fr-par.scw.cloud/djnd/storyteller
    newTag: 'dd7032d13994b441ed43c22470924f57e6516b49'
